### ISSUE TITLE
Why not React Navigation 7.x

### ISSUE THREAD

**Issue by AbhinayMe** [fadyshawky/ReactNativeMagic#1]
React version 7.x is out of beta. I suggest to upgrade. How do I collaborate on this open-source project?

**Comment by fadyshawky** [comment]
please check the package.json it's already react-navigation version 7.x, you can check the contributing section at the end of the readme file.

1. Fork the repository
2. Create your feature branch (git checkout -b feature/AmazingFeature)
3. Commit your changes (git commit -m 'Add some AmazingFeature')
4. Push to the branch (git push origin feature/AmazingFeature)
5. Open a Pull Request
